/** Runtime factories for browser capability identifiers. */

import type {
  BrowserClientId as BrowserClientIdValue,
  BrowserDocumentId as BrowserDocumentIdValue,
  BrowserPageElementRef as BrowserPageElementRefValue,
  BrowserPageId as BrowserPageIdValue,
  BrowserRequestId as BrowserRequestIdValue,
  BrowserScreenshotId as BrowserScreenshotIdValue,
} from './types.ts'

/**
 * Brand a validated provider identity.
 * @param value - provider identity already validated by the browser service.
 * @returns the opaque provider identity.
 */
export function BrowserClientId(value: string): BrowserClientIdValue {
  return value as BrowserClientIdValue
}

/**
 * Brand a Host-generated request identity.
 * @param value - UUID generated by the browser service.
 * @returns the opaque request identity.
 */
export function BrowserRequestId(value: string): BrowserRequestIdValue {
  return value as BrowserRequestIdValue
}

/**
 * Brand a validated current-page snapshot identity.
 * @param value - UUID returned by the browser extension.
 * @returns the opaque page identity.
 */
export function BrowserPageId(value: string): BrowserPageIdValue {
  return value as BrowserPageIdValue
}

/**
 * Brand a validated document identity that remains stable until navigation replaces the document.
 * @param value - UUID returned by the browser extension.
 * @returns the opaque document identity.
 */
export function BrowserDocumentId(value: string): BrowserDocumentIdValue {
  return value as BrowserDocumentIdValue
}

/**
 * Brand a validated screenshot identity used by later visual operations.
 * @param value - UUID returned by the browser extension.
 * @returns the opaque screenshot identity.
 */
export function BrowserScreenshotId(value: string): BrowserScreenshotIdValue {
  return value as BrowserScreenshotIdValue
}

/**
 * Brand a validated current-page element reference.
 * @param value - reference returned by the browser extension.
 * @returns the opaque element reference.
 */
export function BrowserPageElementRef(value: string): BrowserPageElementRefValue {
  return value as BrowserPageElementRefValue
}
